import "../app/globals.css";
import SearchForm from "@/components/SearchForm";
import Link from "next/link";

// Define metadata for the page
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// Component to display the root layout of the app
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Render the root layout
  return (
    <html lang="en">
      <body>
        {/* Display the header */}
        <header className="flex h-16 bg-yellow-300 px-4">
          {/* Create a link to the items page */}
          <Link className="text-yellow-900 m-auto" href="/items">
            {" "}
            MELI{" "}
          </Link>
          {/* Display the search form */}
          <SearchForm />
        </header>
        {/* Display the main content */}
        <main className="m-auto max-w-screen-xl p-4">{children}</main>
      </body>
    </html>
  );
}
